### ISSUE TITLE
More instruction on installation?

### ISSUE THREAD

**Issue by aresundnes** [Ultimaker/meeting-room-display#29]
Hi!
This looks neat, and I've set it up on heroku - but what should the BASIC_AUTH_USER_NAME and BASIC_AUTH_PASSWORD be set to? The login for the google account? Does not seem to work.
When starting up I get a user/pass input field, and after that it fails.

```

2017-12-16T12:07:22.100510+00:00 app[web.1]: I, [2017-12-16T12:07:22.100417 #4]  INFO -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] Started GET "/" for 178.74.8.37 at 2017-12-16 12:07:22 +0000
2017-12-16T12:07:22.101253+00:00 app[web.1]: I, [2017-12-16T12:07:22.101177 #4]  INFO -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] Processing by CalendarsController#index as HTML
2017-12-16T12:07:22.104720+00:00 app[web.1]: I, [2017-12-16T12:07:22.104647 #4]  INFO -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] Completed 500 Internal Server Error in 3ms
2017-12-16T12:07:22.105690+00:00 app[web.1]: F, [2017-12-16T12:07:22.105628 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e]   
2017-12-16T12:07:22.105756+00:00 app[web.1]: F, [2017-12-16T12:07:22.105693 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] Redis::CannotConnectError (Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)):
2017-12-16T12:07:22.105863+00:00 app[web.1]: F, [2017-12-16T12:07:22.105805 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e]   
2017-12-16T12:07:22.105922+00:00 app[web.1]: F, [2017-12-16T12:07:22.105863 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] app/models/google_calendar.rb:48:in `credentials'
2017-12-16T12:07:22.105986+00:00 app[web.1]: F, [2017-12-16T12:07:22.105922 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] app/models/google_calendar.rb:10:in `initialize'
2017-12-16T12:07:22.106045+00:00 app[web.1]: F, [2017-12-16T12:07:22.105986 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] app/controllers/calendars_controller.rb:3:in `new'
2017-12-16T12:07:22.106101+00:00 app[web.1]: F, [2017-12-16T12:07:22.106045 #4] FATAL -- : [e7e4dcc9-e2d0-4d2f-a120-d0d402010a3e] app/controllers/calendars_controller.rb:3:in `index'
 ```

**Comment by jankeesvw** [comment]
Hi @aresundnes, those basic auth credentials are asked for every time you open the meeting room display's website. This is to make it so that not everyone with access to the URL can view your calendar.

When I look at your error log I see that you don't have Redis available on Heroku. 

If you have any questions please reopen this issue.
